### ISSUE TITLE
prefect keeps losing connection to its database

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/prefect-proxy#131]
We see this error very frequently on production - 
`sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: connection is closed`

**Comment by Ishankoradia** [comment]
Changing the following prefect `settings` parameters
`PREFECT_SQLALCHEMY_POOL_SIZE `: 10 (currently 5)
`PREFECT_API_DATABASE_CONNECTION_TIMEOUT`: 20 (currently 5)
`PREFECT_API_DATABASE_TIMEOUT `: 20 (currently 10)

@fatchat

**Comment by Ishankoradia** [comment]
This didn't work. I still see connection errors in worker logs.

**Comment by fatchat** [comment]
doesn't look like this is happening any more
