### ISSUE TITLE
prefect-proxy timeouts

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/prefect-proxy#150]
SNEHA's `dbt seed` task is timing out halfway

```
9|prefect-proxy    | [2024-08-07 12:07:22 +0000] [5464] [CRITICAL] WORKER TIMEOUT (pid:203976)
9|prefect-proxy    | [2024-08-07 12:07:22 +0000] [5464] [WARNING] Worker with pid 203976 was terminated due to signal 6
9|prefect-proxy    | [2024-08-07 12:07:22 +0000] [204020] [INFO] Booting worker with pid: 204020
```

can we look at

https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/47

our uvicorn is at `0.21.1` so it's not the comment about upgrading to `0.11.7` ... but perhaps [some setting](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/47#issuecomment-662879579) ?

https://www.uvicorn.org/settings/#timeouts

https://stackoverflow.com/questions/10855197/gunicorn-how-to-resolve-worker-timeout

**Comment by Ishankoradia** [comment]
I tested on my local with a `dbt seed` that takes a little over 4mins. Running `dbt seed` timed out in the similar way.
The issue is that the dbt seed is a long running process (atleast for sneha) and our timeout dy default is `30 secs`. 

We need to run it via deployments. 

@fatchat
